name: Update Letterboxd Reviews

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 1,4' # Runs every week on Monday and Thursday at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write

jobs:
  update-readme-with-letterboxd:
    name: Update this repo's README with latest reviews from Letterboxd
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Fetch and Update Letterboxd Reviews
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://letterboxd.com/anrath/rss/"
          custom_tags: "filmTitle/letterboxd:filmtitle/,reviewDate/letterboxd:watcheddate/,rating/letterboxd:memberrating/"
          comment_tag_name: MOVIE-LIST
          date_format: "mmm d, yyyy"
          max_post_count: 3
          item_exec: |
            // Remove /anrath from the URL
            post.url = post.url.replace(/\/anrath/g, '');
            const options = { year: 'numeric', month: 'long', day: 'numeric' };
            post.date = post.date.toLocaleDateString('en-US', options);
          template: |
            $newline - [$title]($url) *($date)*
