name: Update Letterboxd Reviews

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # Runs every week on Sunday at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write

jobs:
  update-readme-with-letterboxd:
    name: Update this repo's README with latest reviews from Letterboxd
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Fetch and Update Letterboxd Reviews
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://letterboxd.com/anrath/rss/"
          custom_tags: "filmTitle/letterboxd:filmtitle/,reviewDate/letterboxd:watcheddate/,rating/letterboxd:memberrating/"
          comment_tag_name: MOVIE-LIST
          date_format: "mmm d, yyyy"
          max_post_count: 3
          item_exec: |
            // Remove /anrath from the URL
            post.url = post.url.replace(/\/anrath/g, '');

            // Extracting img.src
            const imgSrcMatch = post.description.match(/<img[^>]+src="([^">]+)"/);
            post.imgSrc = imgSrcMatch ? imgSrcMatch[1] : null;
            post.categories.push(post.imgSrc);

            // Extracting text within the second <p> tag (assuming it's the "Watched on" text)
            const descriptionExtractMatch = post.description.match(/<p>(.*?)<\/p>/g);
            post.descriptionExtractText = descriptionExtractMatch && descriptionExtractMatch.length > 1 ? descriptionExtractMatch[1].replace(/<\/?p>/g, '') : null;

            const autoTextPattern = /Watched on (Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) (January|February|March|April|May|June|July|August|September|October|November|December) \d{1,2}, \d{4}\./;
            if (autoTextPattern.test(post.descriptionExtractText)) {
              post.descriptionExtractText = '';
            }
            post.description = post.descriptionExtractText;

            // Formatting the date
            const options = { year: 'numeric', month: 'long', day: 'numeric' };
            post.date = post.date.toLocaleDateString('en-US', options);

            console.log(post);
          template: |
            <tr>
              <td><a href="$url" target="_blank"><img src="$categories"></a></td>
              <td><a href="$url" target="_blank"><strong>$title ($date)</strong></a><br/>
              $description</td>
            </tr>